# src/config/config.yaml

project:
  name: Plant Disease Detection
  description: Deep learning models for detecting diseases in plants
  version: 1.0.0

seed: 42

paths:
  data: 
    raw: data/raw
    processed: data/processed
  models: model_registry
  logs: trials

training:
  batch_size: 128
  epochs: 50
  learning_rate: 0.001
  optimizer: adam
  loss: categorical_crossentropy
  metrics: [accuracy, AUC, Precision, Recall]
  early_stopping:
    enabled: true
    patience: 10
    monitor: val_loss
  validation_split: 0.2
  test_split: 0.1
  progress_bar: true
  class_weight: "balanced"  # Added this line to enable class weighting
  clip_norm: 1.0 
  clip_value: null
  # Learning rate scheduler
  lr_schedule:
    enabled: false
    # Type can be: warmup_cosine, warmup_exponential, warmup_step, one_cycle, reduce_on_plateau
    type: "warmup_cosine"
    # Number of warmup epochs
    warmup_epochs: 5
    # Minimum learning rate
    min_lr: 1.0e-6
    # For reduce_on_plateau (if used)
    factor: 0.5
    patience: 5

hardware:
  use_metal: true
  mixed_precision: true
  memory_growth: true
  num_parallel_calls: 16
  prefetch_buffer_size: 8

logging:
  level: INFO
  tensorboard: true
  separate_loggers: true

reporting:
  generate_plots: true
  save_confusion_matrix: true
  save_roc_curves: true
  save_precision_recall: true
  generate_html_report: true

# Dataset configuration
data:
  image_size: [224, 224]    # Default image dimensions for preprocessing
  save_splits: true         # Whether to save dataset splits to disk
  use_saved_splits: true   # Whether to use saved splits when available
  splits_dir: "splits"      # Directory name for storing splits
  cache_parsed_images: false  # Whether to cache parsed images in memory


data_augmentation:
  enabled: true
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: true
  vertical_flip: false
  fill_mode: "nearest"
  
  # Augmentation settings
  color_jitter: true        # Enable color space augmentations
  gaussian_noise: true      # Add random Gaussian noise
  noise_stddev: 0.01        # Standard deviation for Gaussian noise
  random_erasing: true      # Enable random erasing (occlusion)
  erasing_prob: 0.1         # Probability of applying random erasing
  perspective_transform: true  # Enable perspective transformations
  perspective_delta: 0.1    # Max distortion for perspective transform
  
  # Batch-level augmentations
  batch_augmentations: true  # Enable batch-level augmentations
  mixup: true               # Enable MixUp augmentation
  mixup_alpha: 0.2          # Alpha parameter for MixUp
  cutmix: true              # Enable CutMix augmentation
  cutmix_alpha: 1.0         # Alpha parameter for CutMix
  
  # Validation transforms
  validation_augmentation: true    # Enable validation-time processing
  validation_resize_factor: 1.14   # Resize factor before center crop

# Add data validation settings
data_validation:
  enabled: true
  min_samples_per_class: 5
  max_class_imbalance_ratio: 10.0
  min_image_dimensions: [32, 32]
  check_corrupt_images: true
  check_duplicates: false
  max_workers: 16
  max_images_to_check: 10000


  # Model quantization settings
  quantization:
    enabled: false
    # Quantization type: "post_training" or "during_training"
    type: "post_training"
    # Quantization format: "int8", "float16", etc.
    format: "int8"
    # Whether to optimize for inference
    optimize_for_inference: true
    # Whether to measure performance after quantization
    measure_performance: true

  # Model pruning settings
  pruning:
    enabled: false
    # Pruning type: "magnitude", "structured", etc.
    type: "magnitude"
    # Target sparsity (percentage of weights to prune)
    target_sparsity: 0.5
    # Whether to perform pruning during training
    during_training: true
    # Pruning schedule: "constant" or "polynomial"
    schedule: "polynomial"
    # Start step for pruning
    start_step: 0
    # End step for pruning
    end_step: 100
    # Pruning frequency (every N steps)
    frequency: 10